# Generated by Django 4.2.5 on 2023-10-02 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_profile_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_deleted',
        ),
    ]
